# Generated by Django 2.1.7 on 2019-03-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busca', models.CharField(max_length=200)),
                ('dtinicio', models.DateTimeField(verbose_name='Início da Busca')),
                ('dtfinal', models.DateTimeField(verbose_name='Fim da Busca')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('twit_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=320)),
                ('created_time', models.DateTimeField()),
                ('retweets', models.IntegerField()),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Processamento')),
            ],
        ),
        migrations.CreateModel(
            name='TweetUser',
            fields=[
                ('twit_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TweetUser'),
        ),
        migrations.AddField(
            model_name='processamento',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Termo'),
        ),
    ]
