# Generated by Django 2.1.7 on 2019-03-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Interrompido'), ('C', 'Concluido')], default='A', max_length=1),
        ),
    ]
