# Generated by Django 2.1.7 on 2019-04-03 05:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_termo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.BigIntegerField()),
                ('favourites', models.BigIntegerField()),
                ('dt', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='tweetuser',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweetuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tweetuser',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='followershistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TweetUser'),
        ),
    ]
