# Generated by Django 2.1.7 on 2019-04-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190403_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='processamento',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
