# Generated by Django 2.1.7 on 2019-04-03 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190403_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('twit_id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=320)),
                ('created_time', models.DateTimeField()),
                ('retweets', models.IntegerField()),
                ('favorites', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TweetInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instante', models.DateTimeField(auto_now_add=True)),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Processamento')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tweet')),
            ],
        ),
        migrations.AlterModelOptions(
            name='followershistory',
            options={'ordering': ('dt',), 'verbose_name': 'Histórico de Seguidores', 'verbose_name_plural': 'Históricos de Seguidores'},
        ),
        migrations.AlterModelOptions(
            name='termo',
            options={'verbose_name': 'Termo de Busca', 'verbose_name_plural': 'Termos de Busca'},
        ),
        migrations.AlterModelOptions(
            name='tweetuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários do Twitter'},
        ),
        migrations.AddField(
            model_name='tweet',
            name='termo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Termo'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TweetUser'),
        ),
    ]
