# Generated by Django 2.1.7 on 2019-04-05 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20190405_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='termo',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('P', 'Processando'), ('I', 'Interrompido'), ('C', 'Concluido')], default='A', max_length=1),
        ),
    ]
