# Generated by Django 2.1.7 on 2019-04-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190405_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='dtinicio',
            field=models.DateTimeField(blank=True, help_text='Deixe em branco caso queira iniciar imediatamente', null=True, verbose_name='Início da Busca'),
        ),
    ]
