# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190405_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetuser',
            name='followers',
            field=models.BigIntegerField(default=0),
        ),
    ]
