# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-13 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tweetuser_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockProcessamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=True)),
                ('dt_inicio', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tweetuser',
            options={'verbose_name': 'Usuário do Twitter', 'verbose_name_plural': 'Usuários do Twitter'},
        ),
        migrations.AlterField(
            model_name='processamento',
            name='termo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Termo'),
        ),
    ]
