# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190413_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetuser',
            options={'ordering': ['twit_id'], 'verbose_name': 'Usuário do Twitter', 'verbose_name_plural': 'Usuários do Twitter'},
        ),
        migrations.AlterField(
            model_name='lockprocessamento',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
