# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-16 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_termo_ult_processamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=30)),
                ('secret', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=30)),
                ('token_secret', models.CharField(max_length=30)),
                ('last_conn', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tweet')),
                ('created_time', models.DateTimeField(null=True)),
            ],
        ),

        migrations.AlterField(
            model_name='tweetuser',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tweetuser',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='retweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TweetUser'),
        ),
    ]

# ALTER TABLE `core_retweet` ADD CONSTRAINT `core_retweet_user_id_bf9acc76_fk_core_tweetuser_twit_id` FOREIGN KEY (`user_id`) REFERENCES `core_tweetuser` (`twit_id`);