# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-22 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191016_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='language',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
