# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191021_2300'),
    ]

    operation = [
        migrations.AddField(
            model_name='retweet',
            name='retweet_id',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
