# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-08 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_retweet_retweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='tipo',
            field=models.CharField(choices=[('I', 'Importação'), ('U', 'Importação User'), ('T', 'Exportação Tags'), ('N', 'Montagem Rede')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='processamento',
            name='twit_id',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='Último Tweet baixado'),
        ),
    ]
