# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200508_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='processo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Processamento'),
        ),
    ]
