# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-26 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tweet_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='geo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
