# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200526_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=640),
        ),
    ]
