# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200704_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='processo',
        ),
        migrations.RemoveField(
            model_name='tweetinput',
            name='instante',
        ),
        migrations.AddField(
            model_name='tweetinput',
            name='termo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Termo'),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='tipo',
            field=models.CharField(choices=[('I', 'Importação'), ('U', 'Importação User'), ('M', 'Match de Tweets orfãos'), ('T', 'Exportação Tags'), ('N', 'Montagem Rede')], default='I', max_length=1),
        ),
    ]
