# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-29 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200704_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='ult_tweet',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
