# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-30 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_termo_ult_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
