# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-30 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_termo_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamento',
            name='twit_id',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='Último Tweet associado'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=740),
        ),
    ]
