# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-02 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201030_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='tipo_busca',
            field=models.CharField(choices=[('I', 'Importação Twitter'), ('U', 'Importação Usuário'), ('G', 'Busca Global'), ('P', 'Busca no Projeto')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='tipo',
            field=models.CharField(choices=[('I', 'Importação'), ('U', 'Importação User'), ('G', 'Busca Global'), ('P', 'Busca no Projeto'), ('M', 'Match de Tweets orfãos'), ('T', 'Exportação Tags'), ('N', 'Montagem Rede')], default='I', max_length=1),
        ),
    ]
