# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-02 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201102_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='tipo_busca',
            field=models.CharField(choices=[('I', 'Importação Twitter'), ('U', 'Importação Usuário'), ('G', 'Busca Global'), ('P', 'Busca no Projeto')], default='I', max_length=1, verbose_name='Tipo da Busca'),
        ),
    ]
