# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-25 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201102_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=2048),
        ),
    ]
