# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-13 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('core', '0027_termo_last_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='tipo',
            field=models.CharField(choices=[('I', 'Importação'), ('U', 'Importação User'), ('G', 'Busca Global'), ('H', 'Busca Histórica'), ('P', 'Busca no Projeto'), ('M', 'Match de Tweets orfãos'), ('T', 'Exportação Tags'), ('N', 'Montagem Rede')], default='I', max_length=1),
        ),
    ]
