# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-13 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220313_1927'),
    ]

    operations = [
        migrations.RunSQL('update core_projeto set grupo_id = 1')
    ]
