# Generated by Django 2.2.28 on 2022-09-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220917_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='parent_id',
            field=models.CharField(blank=True, db_index=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='retweet',
            name='type',
            field=models.CharField(blank=True, choices=[('C', 'Reply'), ('Q', 'Quote'), ('R', 'Retweet')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='retweet',
            name='retweet_id',
            field=models.CharField(blank=True, db_index=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='retweet',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Tweet'),
        ),
    ]
