# Generated by Django 2.2.28 on 2022-09-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20220923_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('P', 'Processando'), ('E', 'Erro'), ('I', 'Interrompido'), ('C', 'Concluido')], default='A', max_length=1),
        ),
    ]
