# Generated by Django 2.2.28 on 2022-10-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_projeto_alcance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LockProcessamento',
        ),
        migrations.AddField(
            model_name='processamento',
            name='status',
            field=models.CharField(choices=[('A', 'Agendado'), ('P', 'Em processamento'), ('C', 'Concluído')], db_index=True, default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='tipo',
            field=models.CharField(choices=[('I', 'Importação'), ('A', 'Importação Premium'), ('U', 'Importação User'), ('G', 'Busca Global'), ('H', 'Busca Histórica'), ('P', 'Busca no Projeto'), ('M', 'Match de Tweets orfãos'), ('T', 'Exportação Tags'), ('J', 'Importação JSON'), ('N', 'Montagem Rede')], default='I', max_length=1),
        ),
    ]
