# Generated by Django 2.2.28 on 2023-06-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20221018_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='tot_registros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='tipo',
            field=models.CharField(choices=[('I', 'Importação'), ('A', 'Importação Premium'), ('U', 'Importação User'), ('G', 'Busca Global'), ('H', 'Busca Histórica'), ('P', 'Busca no Projeto'), ('B', 'Backup JSON'), ('M', 'Match de Tweets orfãos'), ('T', 'Exportação Tags'), ('J', 'Importação JSON'), ('N', 'Montagem Rede')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='tweetuser',
            name='username',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
