# Generated by Django 2.2.28 on 2023-12-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20230604_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='language',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='termo',
            name='tipo_busca',
            field=models.CharField(choices=[('I', 'Importação Regular'), ('D', 'Importação Rapid'), ('A', 'Importação Premium'), ('U', 'Importação Usuário'), ('G', 'Busca Global'), ('P', 'Busca no Projeto')], default='I', max_length=1, verbose_name='Tipo da Busca'),
        ),
    ]
