# Generated by Django 2.2.28 on 2024-04-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20231207_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='followershistory',
            name='following',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='imprints',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='quotes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='followershistory',
            name='favourites',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='followershistory',
            name='followers',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='favorites',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweets',
            field=models.IntegerField(null=True),
        ),
    ]
