# Generated by Django 2.2.28 on 2024-04-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20240429_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='estimativa',
            field=models.IntegerField(default=0, verbose_name='Total Estimado'),
        ),
        migrations.AlterField(
            model_name='termo',
            name='tipo_busca',
            field=models.CharField(choices=[('A', 'Importação Premium'), ('U', 'Importação Usuário'), ('G', 'Busca Global'), ('P', 'Busca no Projeto')], default='I', max_length=1, verbose_name='Tipo da Busca'),
        ),
    ]
