# Generated by Django 2.2.28 on 2024-04-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20240430_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tot_twits',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Lido'),
        ),
    ]
