# Generated by Django 2.2.28 on 2024-05-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_projeto_tot_twits'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_user', to='core.TweetUser'),
        ),
    ]
