# Generated by Django 3.2.25 on 2024-07-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20240504_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('P', 'Processando'), ('E', 'Erro'), ('I', 'Interrompido'), ('C', 'Concluido')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
