# Generated by Django 3.2.25 on 2024-07-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20240706_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='stopwords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='tipo',
            field=models.CharField(choices=[('I', 'Importação'), ('A', 'Importação Premium'), ('D', 'Importação Rapid'), ('U', 'Importação User'), ('G', 'Busca Global'), ('O', 'OpenSearch'), ('P', 'Busca no Projeto'), ('B', 'Backup JSON'), ('E', 'Calcula Estimativa'), ('M', 'Match de Tweets orfãos'), ('T', 'Exportação Tags'), ('J', 'Importação JSON'), ('N', 'Montagem Rede')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='termo',
            name='tipo_busca',
            field=models.CharField(choices=[('A', 'Importação Premium'), ('U', 'Importação Usuário'), ('G', 'Busca Global'), ('O', 'OpenSearch'), ('P', 'Busca no Projeto')], default='I', max_length=1, verbose_name='Tipo da Busca'),
        ),
    ]
