# Generated by Django 3.2.25 on 2025-05-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20250416_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='descritivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='termo',
            name='dtfinal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim da Busca'),
        ),
    ]
