# Generated by Django 3.2.25 on 2025-05-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20250512_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='prefix',
            field=models.CharField(blank=True, max_length=20, verbose_name='Elastic Prefix'),
        ),
    ]
