# Generated by Django 3.2.25 on 2025-06-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0046_projeto_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'verbose_name': 'Projeto de Monitoramento', 'verbose_name_plural': 'Monitoramentos'},
        ),
        migrations.AddField(
            model_name='termo',
            name='busca_complementar',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='eixo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.eixo'),
        ),
    ]
