# Generated by Django 3.2.25 on 2025-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20250626_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamento',
            name='tipo',
            field=models.CharField(choices=[('I', 'Importação'), ('A', 'Twitter Search'), ('F', 'Twitter Full'), ('Y', 'Importação Youtube'), ('U', 'Importação User'), ('G', 'Busca Global'), ('O', 'OpenSearch'), ('P', 'Busca no Projeto'), ('B', 'Backup JSON'), ('E', 'Calcula Estimativa'), ('M', 'Match de Tweets orfãos'), ('T', 'Exportação Tags'), ('J', 'Importação JSON'), ('N', 'Montagem Rede')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='termo',
            name='busca_complementar',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Busca Complementar'),
        ),
        migrations.AlterField(
            model_name='termo',
            name='tipo_busca',
            field=models.CharField(choices=[('A', 'Importação Premium'), ('F', 'Importação Full Archive'), ('U', 'Importação Usuário'), ('G', 'Busca Global'), ('O', 'OpenSearch'), ('P', 'Busca no Projeto')], default='I', max_length=1, verbose_name='Tipo da Busca'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(),
        ),
    ]
