# Generated by Django 3.2.25 on 2025-07-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20250701_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='prim_tweet',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
