# Generated by Django 3.2.25 on 2025-07-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_termo_prim_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='dtinicio',
            field=models.DateTimeField(verbose_name='Início da Busca'),
        ),
    ]
