# Generated by Django 3.2.25 on 2025-08-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_termo_dtinicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='retweets',
            field=models.BooleanField(default=False, verbose_name='Incluir retweets'),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='tipo',
            field=models.CharField(choices=[('I', 'Importação'), ('A', 'Twitter Search'), ('F', 'Twitter Full'), ('C', 'Twitter Contínua'), ('Y', 'Importação Youtube'), ('U', 'Importação User'), ('G', 'Busca Global'), ('O', 'OpenSearch'), ('P', 'Busca no Projeto'), ('B', 'Backup JSON'), ('E', 'Calcula Estimativa'), ('M', 'Match de Tweets orfãos'), ('T', 'Exportação Tags'), ('J', 'Importação JSON'), ('N', 'Montagem Rede')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='termo',
            name='tipo_busca',
            field=models.CharField(choices=[('A', 'Importação Premium'), ('F', 'Importação Full Archive'), ('U', 'Importação Usuário'), ('G', 'Busca Global'), ('O', 'OpenSearch'), ('P', 'Busca no Projeto')], default='F', max_length=1, verbose_name='Tipo da Busca'),
        ),
    ]
