# Generated by Django 3.2.25 on 2025-09-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20250821_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observação sobre a coleta'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('P', 'Processando'), ('E', 'Erro'), ('I', 'Fila'), ('X', 'Interrompido'), ('C', 'Concluido')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='termo',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('P', 'Processando'), ('E', 'Erro'), ('I', 'Fila'), ('X', 'Interrompido'), ('C', 'Concluido')], default='A', max_length=1),
        ),
    ]
