# Generated by Django 3.2.25 on 2025-10-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20250916_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='F', max_length=1)),
                ('status', models.CharField(default='A', max_length=1)),
                ('twit_id', models.CharField(blank=True, max_length=21, null=True)),
                ('dt_inicial', models.DateField(blank=True, null=True, verbose_name='Dt.Inicial')),
                ('dt_final', models.DateField(blank=True, null=True, verbose_name='Dt.Final')),
                ('since_id', models.CharField(blank=True, max_length=21, null=True)),
                ('until_id', models.CharField(blank=True, max_length=21, null=True)),
                ('limite', models.IntegerField(blank=True, null=True)),
                ('termo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.termo')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos Especiais',
            },
        ),
        migrations.DeleteModel(
            name='Credencial',
        ),
        migrations.AlterField(
            model_name='processamento',
            name='tipo',
            field=models.CharField(choices=[('I', 'Importação'), ('A', 'Twitter Search'), ('F', 'Twitter Full'), ('C', 'Twitter Contínua'), ('Y', 'Importação Youtube'), ('U', 'Importação User'), ('G', 'Busca Global'), ('O', 'OpenSearch'), ('P', 'Busca no Projeto'), ('B', 'Backup JSON'), ('E', 'Calcula Estimativa'), ('H', 'Match de Tweets orfãos'), ('T', 'Exportação Tags'), ('J', 'Importação JSON'), ('N', 'Montagem Rede')], default='I', max_length=1),
        ),
    ]
