# Generated by Django 3.2.25 on 2025-10-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20251030_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('A', 'Agendado'), ('P', 'Processando'), ('C', 'Concluído')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo',
            field=models.CharField(choices=[('F', 'Mais Recentes'), ('L', 'Mais Relevantes'), ('R', 'Retweets'), ('M', 'Comentários')], default='F', max_length=1),
        ),
    ]
