# Generated by Django 3.2.25 on 2025-10-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20251030_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='dt_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dt.Final'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='dt_inicial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dt.Inicial'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='limite',
            field=models.IntegerField(default=10000),
        ),
    ]
