# Generated by Django 3.2.25 on 2025-10-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20251031_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='dt_corte',
            field=models.DateTimeField(blank=True, help_text='Data da menor data obtida', null=True, verbose_name='Dt.Corte'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('A', 'Agendado'), ('P', 'Processando'), ('C', 'Concluído'), ('E', 'Erro na Captura')], default='A', max_length=1),
        ),
    ]
