# Generated by Django 3.2.25 on 2026-03-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20251031_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamento',
            name='status',
            field=models.CharField(choices=[('A', 'Agendado'), ('P', 'Procesando'), ('C', 'Concluido'), ('E', 'Finalizado com erro')], db_index=True, default='A', max_length=1),
        ),
    ]
