# Generated by Django 4.2.30 on 2026-08-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_canal_verificado'),
        ('core', '0057_alter_processamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='lista_canais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='telegram.lista'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Interrompido'), ('C', 'Concluido')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='termo',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('P', 'Processando'), ('E', 'Erro'), ('I', 'Fila'), ('X', 'Interrompido'), ('C', 'Concluido')], default='A', max_length=1, verbose_name='Status Twitter'),
        ),
        migrations.CreateModel(
            name='TermoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('P', 'Processando'), ('E', 'Erro'), ('I', 'Fila'), ('X', 'Interrompido'), ('C', 'Concluido')], default='A', max_length=1)),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rede')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.termo')),
                ('ult_processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.processamento')),
            ],
            options={
                'verbose_name': 'Status da Busca',
                'verbose_name_plural': 'Status da Busca',
            },
        ),
    ]
