# Generated by Django 4.2.30 on 2026-08-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_projeto_lista_canais_alter_projeto_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termostatus',
            name='ult_processo',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Processo Externo'),
        ),
    ]
