# Generated by Django 4.2.30 on 2026-08-21 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('id_numerico', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('num_participantes', models.IntegerField(default=0, verbose_name='Tot.Participantes')),
                ('num_mensagens', models.BigIntegerField(default=0, verbose_name='Tot.Mensagens')),
                ('megagroup', models.BooleanField(default=False)),
                ('verificado', models.BooleanField(default=False)),
                ('dt_ultima_carga', models.DateTimeField(blank=True, null=True, verbose_name='Útlima carga')),
                ('access_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('P', 'Em processamento'), ('D', 'Desativado')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('publica', models.BooleanField(default=False, verbose_name='Qualquer usuário pode utilizá-la')),
                ('canais', models.ManyToManyField(blank=True, to='telegram.canal')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='canal',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='telegram.categoria'),
        ),
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('api_id', models.IntegerField()),
                ('api_hash', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
