# Generated by Django 4.2.30 on 2026-08-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='verificado',
            field=models.BooleanField(default=False, verbose_name='Verificado pelo Telegram'),
        ),
    ]
