# Generated by Django 4.2.30 on 2026-08-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_canal_verificado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikeys',
            options={'verbose_name': 'Chave de API', 'verbose_name_plural': 'Chaves de API'},
        ),
        migrations.AlterModelOptions(
            name='canal',
            options={'verbose_name_plural': 'Canais'},
        ),
        migrations.AddField(
            model_name='canal',
            name='dtcriacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dt.Criação'),
        ),
        migrations.AddField(
            model_name='canal',
            name='ultima_mensagem',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
