# Generated by Django 4.2.30 on 2026-08-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_apikeys_options_alter_canal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeys',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('E', 'Inválida')], default='A', max_length=1),
        ),
    ]
