# Generated by Django 4.2.30 on 2026-09-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_apikeys_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeys',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone (+PaisNumero)'),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='canal',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('P', 'Em processamento'), ('D', 'Não existe mais'), ('I', 'Inativo')], default='A', max_length=1),
        ),
    ]
