# Generated by Django 4.2.30 on 2026-09-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_apikeys_telefone_alter_apikeys_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização'),
        ),
    ]
